/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_BRUSHLESS_PB_H_INCLUDED
#define PB_BRUSHLESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Commands {
    Commands_STOP = 0,
    Commands_RUN = 1,
    Commands_BREAK = 2
} Commands;

/* Struct definitions */
typedef struct _MainBoardToBrushless {
    Commands command; /* Brushless command */
    float speed; /* m.s-1 */
} MainBoardToBrushless;

typedef struct _BrushlessToMainBoard {
    uint32_t error_count; /* Number of SPI transmission errors */
    float measured_speed; /* m.s-1 */
} BrushlessToMainBoard;

typedef struct _MainBoardToDribbler {
    Commands command;
    float speed;
} MainBoardToDribbler;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Commands_MIN Commands_STOP
#define _Commands_MAX Commands_BREAK
#define _Commands_ARRAYSIZE ((Commands)(Commands_BREAK+1))

#define MainBoardToBrushless_command_ENUMTYPE Commands


#define MainBoardToDribbler_command_ENUMTYPE Commands


/* Initializer values for message structs */
#define MainBoardToBrushless_init_default        {_Commands_MIN, 0}
#define BrushlessToMainBoard_init_default        {0, 0}
#define MainBoardToDribbler_init_default         {_Commands_MIN, 0}
#define MainBoardToBrushless_init_zero           {_Commands_MIN, 0}
#define BrushlessToMainBoard_init_zero           {0, 0}
#define MainBoardToDribbler_init_zero            {_Commands_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MainBoardToBrushless_command_tag         1
#define MainBoardToBrushless_speed_tag           2
#define BrushlessToMainBoard_error_count_tag     1
#define BrushlessToMainBoard_measured_speed_tag  2
#define MainBoardToDribbler_command_tag          1
#define MainBoardToDribbler_speed_tag            2

/* Struct field encoding specification for nanopb */
#define MainBoardToBrushless_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2)
#define MainBoardToBrushless_CALLBACK NULL
#define MainBoardToBrushless_DEFAULT NULL

#define BrushlessToMainBoard_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   error_count,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    measured_speed,    2)
#define BrushlessToMainBoard_CALLBACK NULL
#define BrushlessToMainBoard_DEFAULT NULL

#define MainBoardToDribbler_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2)
#define MainBoardToDribbler_CALLBACK NULL
#define MainBoardToDribbler_DEFAULT NULL

extern const pb_msgdesc_t MainBoardToBrushless_msg;
extern const pb_msgdesc_t BrushlessToMainBoard_msg;
extern const pb_msgdesc_t MainBoardToDribbler_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MainBoardToBrushless_fields &MainBoardToBrushless_msg
#define BrushlessToMainBoard_fields &BrushlessToMainBoard_msg
#define MainBoardToDribbler_fields &MainBoardToDribbler_msg

/* Maximum encoded size of messages (where known) */
#define BrushlessToMainBoard_size                11
#define MainBoardToBrushless_size                7
#define MainBoardToDribbler_size                 7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
