/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_BRUSHLESS_PB_H_INCLUDED
#define PB_BRUSHLESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Commands {
    Commands_STOP = 0,
    Commands_RUN = 1,
    Commands_BREAK = 2
} Commands;

/* Struct definitions */
typedef struct _MainboardToBrushless {
    Commands command; /* Brushless command */
    float speed; /* m.s-1 */
} MainboardToBrushless;

typedef struct _BrushlessToMainboard {
    uint32_t error_count; /* Number of SPI transmission errors */
    float measured_speed; /* m.s-1 */
} BrushlessToMainboard;

typedef struct _MainboardToDribbler {
    Commands command;
    float speed;
} MainboardToDribbler;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Commands_MIN Commands_STOP
#define _Commands_MAX Commands_BREAK
#define _Commands_ARRAYSIZE ((Commands)(Commands_BREAK+1))

#define MainboardToBrushless_command_ENUMTYPE Commands


#define MainboardToDribbler_command_ENUMTYPE Commands


/* Initializer values for message structs */
#define MainboardToBrushless_init_default        {_Commands_MIN, 0}
#define BrushlessToMainboard_init_default        {0, 0}
#define MainboardToDribbler_init_default         {_Commands_MIN, 0}
#define MainboardToBrushless_init_zero           {_Commands_MIN, 0}
#define BrushlessToMainboard_init_zero           {0, 0}
#define MainboardToDribbler_init_zero            {_Commands_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MainboardToBrushless_command_tag         1
#define MainboardToBrushless_speed_tag           2
#define BrushlessToMainboard_error_count_tag     1
#define BrushlessToMainboard_measured_speed_tag  2
#define MainboardToDribbler_command_tag          1
#define MainboardToDribbler_speed_tag            2

/* Struct field encoding specification for nanopb */
#define MainboardToBrushless_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2)
#define MainboardToBrushless_CALLBACK NULL
#define MainboardToBrushless_DEFAULT NULL

#define BrushlessToMainboard_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   error_count,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    measured_speed,    2)
#define BrushlessToMainboard_CALLBACK NULL
#define BrushlessToMainboard_DEFAULT NULL

#define MainboardToDribbler_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2)
#define MainboardToDribbler_CALLBACK NULL
#define MainboardToDribbler_DEFAULT NULL

extern const pb_msgdesc_t MainboardToBrushless_msg;
extern const pb_msgdesc_t BrushlessToMainboard_msg;
extern const pb_msgdesc_t MainboardToDribbler_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MainboardToBrushless_fields &MainboardToBrushless_msg
#define BrushlessToMainboard_fields &BrushlessToMainboard_msg
#define MainboardToDribbler_fields &MainboardToDribbler_msg

/* Maximum encoded size of messages (where known) */
#define BrushlessToMainboard_size                11
#define MainboardToBrushless_size                7
#define MainboardToDribbler_size                 7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
