/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "brushless.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MainBoardToBrushless, MainBoardToBrushless, AUTO)


PB_BIND(BrushlessToMainBoard, BrushlessToMainBoard, AUTO)


PB_BIND(MainBoardToDribbler, MainBoardToDribbler, AUTO)




