/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "brushless.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MainboardToBrushless, MainboardToBrushless, AUTO)


PB_BIND(BrushlessToMainboard, BrushlessToMainboard, AUTO)


PB_BIND(MainboardToDribbler, MainboardToDribbler, AUTO)




